module.exports = {
  DEFAULT_HOLD_DURATION_MINUTES: 15,
  MIN_HOLD_DURATION_MINUTES: 5,
  MAX_HOLD_DURATION_MINUTES: 60,
  SWEEPER_INTERVAL_MS: 30000, // 30 seconds
  REMINDER_THRESHOLD_MINUTES: 5,

  HOLD_STATUS: {
    ACTIVE: 'active',
    ACCEPTED: 'accepted',
    EXPIRED: 'expired',
    DECLINED: 'declined',
    CANCELLED: 'cancelled',
  },

  WAITLIST_STATUS: {
    WAITING: 'waiting',
    ELIGIBLE: 'eligible',
    HOLD_ACTIVE: 'hold_active',
    NOTIFIED: 'notified',
    PROMOTED: 'promoted',
    EXPIRED: 'expired',
    DECLINED: 'declined',
    SKIPPED: 'skipped',
    INELIGIBLE: 'ineligible',
  },

  AUDIT_ACTIONS: {
    WAITLIST_JOINED: 'WAITLIST_JOINED',
    ELIGIBILITY_CHECKED: 'ELIGIBILITY_CHECKED',
    SEAT_HELD: 'SEAT_HELD',
    NOTIFICATION_SENT: 'NOTIFICATION_SENT',
    REMINDER_SENT: 'REMINDER_SENT',
    HOLD_ACCEPTED: 'HOLD_ACCEPTED',
    PAYMENT_STARTED: 'PAYMENT_STARTED',
    PAYMENT_VERIFIED: 'PAYMENT_VERIFIED',
    REGISTRATION_CONFIRMED: 'REGISTRATION_CONFIRMED',
    HOLD_EXPIRED: 'HOLD_EXPIRED',
    HOLD_DECLINED: 'HOLD_DECLINED',
    SEAT_RELEASED: 'SEAT_RELEASED',
    NEXT_PROMOTED: 'NEXT_PROMOTED',
    PROMOTION_SKIPPED: 'PROMOTION_SKIPPED',
    MANUAL_PROMOTION: 'MANUAL_PROMOTION',
  },
};
